### ISSUE TITLE
Unexpected token when using destructured arguments with arrow functions

### ISSUE THREAD

**Issue by kunalgolani** [babel/babel-eslint#157]
```js
function(someArray) {
  someArray.filter({someProp} => !someProp.shouldRemove);
}
```

**Comment by sebmck** [comment]
That's definently illegal syntax. I also cannot reproduce this in Espree (the parser that ESLint uses): 

```
> require("espree").parse("someArray.filter({someProp} => !someProp.shouldRemove);", { ecmaFeatures: { arrowFunctions: true, destructuring: true } });
Error: Line 1: Unexpected token =>
    at throwError (/Users/sebmck/Projects/babel/node_modules/espree/espree.js:2070:17)
    at throwUnexpected (/Users/sebmck/Projects/babel/node_modules/espree/espree.js:2133:5)
    at parseAssignmentExpression (/Users/sebmck/Projects/babel/node_modules/espree/espree.js:3530:17)
    at parseSpreadOrAssignmentExpression (/Users/sebmck/Projects/babel/node_modules/espree/espree.js:2931:12)
    at parseArguments (/Users/sebmck/Projects/babel/node_modules/espree/espree.js:2909:19)
    at parseLeftHandSideExpressionAllowCall (/Users/sebmck/Projects/babel/node_modules/espree/espree.js:3001:20)
    at parsePostfixExpression (/Users/sebmck/Projects/babel/node_modules/espree/espree.js:3044:12)
    at parseUnaryExpression (/Users/sebmck/Projects/babel/node_modules/espree/espree.js:3072:16)
    at parseBinaryExpression (/Users/sebmck/Projects/babel/node_modules/espree/espree.js:3196:12)
    at parseConditionalExpression (/Users/sebmck/Projects/babel/node_modules/espree/espree.js:3257:12)
```

**Comment by kunalgolani** [comment]
Sorry, my bad. Should be enclosed in braces:
`someArray.filter(({someProp}) => !someProp.shouldRemove);`
