### ISSUE TITLE
ReferenceError: couldn't resolve escope/referencer

### ISSUE THREAD

**Issue by aayush-practo** [babel/babel-eslint#195]
I am using babel-eslint@4.1.3 parser for converting es6 to es5 in my sail js application along with sails-hook-eslint@1.0.3 for linting the js code. Sails lift is giving me following error.

```
ReferenceError: couldn't resolve escope/referencer
    at monkeypatch (/home/vagrant/www/swaggerApp/node_modules/babel-eslint/index.js:73:11)
    at Object.exports.parse (/home/vagrant/www/swaggerApp/node_modules/babel-eslint/index.js:374:5)
    at parse (/home/vagrant/www/swaggerApp/node_modules/sails-hook-eslint/node_modules/eslint/lib/eslint.js:462:27)
    at EventEmitter.module.exports.api.verify (/home/vagrant/www/swaggerApp/node_modules/sails-hook-eslint/node_modules/eslint/lib/eslint.js:614:15)
    at processFile (/home/vagrant/www/swaggerApp/node_modules/sails-hook-eslint/node_modules/eslint/lib/cli-engine.js:193:27)
    at /home/vagrant/www/swaggerApp/node_modules/sails-hook-eslint/node_modules/eslint/lib/cli-engine.js:293:26
    at /home/vagrant/www/swaggerApp/node_modules/sails-hook-eslint/node_modules/eslint/lib/util/traverse.js:61:17
    at Array.forEach (native)
    at traverse (/home/vagrant/www/swaggerApp/node_modules/sails-hook-eslint/node_modules/eslint/lib/util/traverse.js:41:54)
    at /home/vagrant/www/swaggerApp/node_modules/sails-hook-eslint/node_modules/eslint/lib/util/traverse.js:63:17
    at Array.forEach (native)
    at traverse (/home/vagrant/www/swaggerApp/node_modules/sails-hook-eslint/node_modules/eslint/lib/util/traverse.js:41:54)
    at walk (/home/vagrant/www/swaggerApp/node_modules/sails-hook-eslint/node_modules/eslint/lib/util/traverse.js:83:9)
    at /home/vagrant/www/swaggerApp/node_modules/sails-hook-eslint/node_modules/eslint/lib/util/traverse.js:102:9
    at Array.forEach (native)
    at traverse (/home/vagrant/www/swaggerApp/node_modules/sails-hook-eslint/node_modules/eslint/lib/util/traverse.js:101:11)
```
I looked into ``` node_modules/babel-eslint/index.js ``` and there a directory was getting referenced which did not exist.
``` javascript
// monkeypatch escope/referencer
  var referencerLoc;
  try {
    referencerLoc = Module._resolveFilename("./referencer", escopeMod);
  } catch (err) {
    throw new ReferenceError("couldn't resolve escope/referencer");
  }
  var referencerMod = createModule(referencerLoc);
  var referencer = require(referencerLoc);

// reference Definition
  var definitionLoc;
  try {
    definitionLoc = Module._resolveFilename("./definition", referencerMod);
  } catch (err) {
    throw new ReferenceError("couldn't resolve escope/definition");
  }
  var Definition = require(definitionLoc).Definition;
```

``` ./referencer ``` and ```./definition``` does not exist. I wanted to know the possible solution for the problem.

**Comment by hzoo** [comment]
I don't think escope change or anything or if you have a different one then it's expecting. It could potentially be an npm issue as well? Will have to look into it.

**Comment by aayush-practo** [comment]
I am using npm@0.10.37, sails-hook-eslint@1.0.3, eslint@1.7.3 and escope@3.2.0

**Comment by aayush-practo** [comment]
@hzoo any updates for the ReferenceError?

**Comment by hzoo** [comment]
I think you mean node 0.10.37? it's just weird since escope hasn't updated at all so nothing should of changed. What npm version are you using? Can you try `rm -rf node_modules && npm cache clean && npm install` again? Were you using babel-eslint before this or is it a new addition?

**Comment by aayush-practo** [comment]
npm version I am using is 1.4.28. I tried the command ```rm -rf node_modules && npm cache clean && npm install``` its still showing the same error. Babel-eslint is the new addition, I am using it for the first time.

**Comment by hzoo** [comment]
Can you try using npm 2 or 3? Not sure if that will fix it but we haven't had anyone else say they have issues yet

**Comment by blainekasten** [comment]
We've ran into this a lot at Hudl lately. It just appeared one day and caused a bunch of problems. Some of use npm2, some use npm3. Both seem to be affected.

**Comment by mmoriar1** [comment]
FYI, the resolution for me was to upgrade `grunt-eslint`. The `babel-eslint` in the stacktrace was a red herring, it was referencing `eslint` from `grunt-eslint`. Hope this helps anyone, this was an annoying one to debug!

**Comment by ndabAP** [comment]
The solution from @mmoriar1 didn' work for me. I'm also using Sails.js.
