### ISSUE TITLE
Crash with arrow functions and strict rule

### ISSUE THREAD

**Issue by btmills** [babel/babel-eslint#20]
Moving this from eslint/eslint#1906.

```sh
$ mkdir test
$ cd test
$ npm i eslint babel-eslint
```

Save the following files in the `test` directory:

```js
// test.js
'use strict';

() => foo;
```

```js
// config-espree.json
{
	"rules": {
		"strict": [2, "global"]
	},
	"ecmaFeatures": {
		"arrowFunctions": true
	}
}
```

```js
// config-babel.json
{
	"parser": "babel-eslint",
	"rules": {
		"strict": [2, "global"]
	}
}
```

Then run ESLint using each config:

```sh
$ node_modules/.bin/eslint --reset --no-eslintrc -c config-espree.json test.js

$ node_modules/.bin/eslint --reset --no-eslintrc -c config-babel.json test.js
~/code/babel/babel-eslint-test/node_modules/eslint/lib/rules/strict.js:33
    for (i = 0; i < statements.length; i++) {
                              ^
TypeError: Cannot read property 'length' of undefined
    at getUseStrictDirectives (~/code/babel/babel-eslint-test/node_modules/eslint/lib/rules/strict.js:33:31)
    at EventEmitter.modes.global.FunctionExpression (~/code/babel/babel-eslint-test/node_modules/eslint/lib/rules/strict.js:178:20)
    at EventEmitter.emit (events.js:107:17)
    at Controller.controller.traverse.enter (~/code/babel/babel-eslint-test/node_modules/eslint/lib/eslint.js:683:25)
    at Controller.__execute (~/code/babel/babel-eslint-test/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (~/code/babel/babel-eslint-test/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (~/code/babel/babel-eslint-test/node_modules/eslint/lib/eslint.js:676:24)
    at processFile (~/code/babel/babel-eslint-test/node_modules/eslint/lib/cli-engine.js:172:23)
    at ~/code/babel/babel-eslint-test/node_modules/eslint/lib/cli-engine.js:271:26
    at walk (~/code/babel/babel-eslint-test/node_modules/eslint/lib/util/traverse.js:81:9
```

Perhaps because the `ArrowFunctionExpression` is getting turned into a `FunctionExpression`?

**Comment by sebmck** [comment]
Ugh, sorry about people reporting issues on the eslint repo. I thought I made it pretty clear in the README with:

> Please note that this is experimental and may have numerous bugs

I'll try and make it more clear.
