### ISSUE TITLE
Strange "Maximum call stack size exceeded" exception

### ISSUE THREAD

**Issue by voronianski** [babel/babel-eslint#214]
Using  latest eslint version:

```bash
$ node_modules/.bin/eslint -v
v1.10.1
```

Running through Makefile command:

```bash
ESLINT_CMD = node_modules/.bin/eslint
SRC_JS = $(shell find src -name "*.js")

lint:
	$(ESLINT_CMD) $(SRC_JS)
```

Got this exception everytime:

```bash
make lint
node_modules/.bin/eslint src/__tests__/createActions-test.js src/__tests__/exampleFlux-test.js src/__tests__/Flux-test.js src/__tests__/Store-test.js src/addons/__tests__/addContext.js src/addons/__tests__/connect-test.js src/addons/__tests__/FluxComponent-test.js src/addons/__tests__/reactComponentMethods-test.js src/addons/__tests__/TestUtils-test.js src/addons/connect.js src/addons/FluxComponent.js src/addons/react-native.js src/addons/react.js src/addons/reactComponentMethods.js src/addons/TestUtils.js src/createActions.js src/Flux.js src/Store.js src/test/init.js
/Users/dmitri/github/flummox/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:70
        if (node == null) {
                 ^
RangeError: Maximum call stack size exceeded
    at keys (native)
    at Referencer.Visitor.visitChildren (/Users/dmitri/github/flummox/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:78:24)
    at Referencer.Visitor.visit (/Users/dmitri/github/flummox/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (/Users/dmitri/github/flummox/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:93:26)
    at Referencer.Visitor.visit (/Users/dmitri/github/flummox/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (/Users/dmitri/github/flummox/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:88:38)
    at Referencer.Visitor.visit (/Users/dmitri/github/flummox/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (/Users/dmitri/github/flummox/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:93:26)
    at Referencer.Visitor.visit (/Users/dmitri/github/flummox/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (/Users/dmitri/github/flummox/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:88:38)
make: *** [lint] Error 1
```

Any ideas? Thanks!

**Comment by voronianski** [comment]
OOPS! WRONG REPO!

**Comment by voronianski** [comment]
it looks like it's correct repo if follow this discussion - https://github.com/eslint/eslint/issues/4485

**Comment by voronianski** [comment]
updated to latest `4.1.6` and that solved the issue.
