### ISSUE TITLE
Empty curly brackets on destructuring function params raises TypeError

### ISSUE THREAD

**Issue by chibicode** [babel/babel-eslint#238]
Hi, thanks for babel-eslint. I'm currently having some issues w/ babel-eslint, and not sure if this is a bug on eslint or on babel-eslint. Consider the following:

```js
const foo = ({}) => a
```

Running eslint on above w/ babel-eslint gives me this **error** (not just that the syntax is wrong, but linting itself fails and aborts):

```
/Users/shu/code/debug-eslint/node_modules/eslint/lib/token-store.js:90
        return tokens[starts[node.range[0]] - (skip || 0) - 1];
                                 ^

TypeError: Cannot read property 'range' of undefined
    at SourceCode.api.getTokenBefore (/Users/shu/code/debug-eslint/node_modules/eslint/lib/token-store.js:90:34)
    at EventEmitter.api.(anonymous function) [as getTokenBefore] (/Users/shu/code/debug-eslint/node_modules/eslint/lib/eslint.js:888:48)
    at RuleContext.(anonymous function) [as getTokenBefore] (/Users/shu/code/debug-eslint/node_modules/eslint/lib/rule-context.js:108:33)
    at EventEmitter.ObjectPattern (/Users/shu/code/debug-eslint/node_modules/eslint-plugin-standard/rules/object-curly-even-spacing.js:180:27)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/Users/shu/code/debug-eslint/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CommentEventGenerator.enterNode (/Users/shu/code/debug-eslint/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.controller.traverse.enter (/Users/shu/code/debug-eslint/node_modules/eslint/lib/eslint.js:767:36)
    at Controller.__execute (/Users/shu/code/debug-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
```

The error is never caught, so the error gets raised all the way to my editor:

![image](https://cloud.githubusercontent.com/assets/992008/12531546/5cbf98fe-c1b2-11e5-81ef-685512f7a356.png)

Of course, the following works:

```js
const foo = ({ a }) => a
```

Running it:

```
/Users/shu/code/debug-eslint/pass.js
  1:7  error  "foo" is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

## Reproduce Locally

**I created a repo to reproduce this.** You can check out the repo here: https://github.com/chibicode/debug-eslint

#### package.json

```json
{
  "private": true,
  "devDependencies": {
    "babel-eslint": "^4.1.6",
    "eslint": "^1.10.3",
    "eslint-config-standard": "^4.4.0",
    "eslint-plugin-standard": "^1.3.1"
  }
}
```

#### .eslintrc

```json
{
  "extends": "standard",
  "parser": "babel-eslint"
}
```

**Comment by danez** [comment]
I couldn't reproduce this with latest eslint and babel-eslint 6. You might consider upgrading eslint and babel-eslint. If the error still show up please reopen.

**Comment by danez** [comment]
Ok I think i see what is the error, it is a problem with the rule `object-curly-even-spacing` which assumes, that an object always needs to have properties defined.

**Comment by danez** [comment]
I tried and I could reproduce with eslint-plugin-standard@1.3.1, but it works with 1.3.2. :)
