### ISSUE TITLE
Calling escope.analyze with babel-eslint unnecessarily requires the opts argument

### ISSUE THREAD

**Issue by Standard8** [babel/babel-eslint#470]
In eslint-plugin-mozilla, we're doing:

```js
let scopeManager = escope.analyze(ast);
```

However, this fails with:

```console
Cannot set property 'ecmaVersion' of undefined
TypeError: Cannot set property 'ecmaVersion' of undefined
    at Object.escope.analyze (/Users/mark/dev/normandy/recipe-client-addon/node_modules/babel-eslint/index.js:65:22)
    at Object.getGlobalsForFile (/Users/mark/dev/normandy/recipe-client-addon/node_modules/eslint-plugin-mozilla/lib/globals.js:153:31)
    at importHead (/Users/mark/dev/normandy/recipe-client-addon/node_modules/eslint-plugin-mozilla/lib/rules/import-headjs-globals.js:32:30)
    at EventEmitter.Program (/Users/mark/dev/normandy/recipe-client-addon/node_modules/eslint-plugin-mozilla/lib/rules/import-headjs-globals.js:44:9)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:191:7)
    at NodeEventGenerator.applySelector (/Users/mark/dev/normandy/recipe-client-addon/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/Users/mark/dev/normandy/recipe-client-addon/node_modules/eslint/lib/util/node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode (/Users/mark/dev/normandy/recipe-client-addon/node_modules/eslint/lib/util/node-event-generator.js:308:14)
    at CodePathAnalyzer.enterNode (/Users/mark/dev/normandy/recipe-client-addon/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:602:23)
    at CommentEventGenerator.enterNode (/Users/mark/dev/normandy/recipe-client-addon/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
```

If I change it to:

```js
let scopeManager = escope.analyze(ast, {});
```

then it works & passes.

Since the former works with the main eslint, I'd expect it to work here as well.

**Comment by Standard8** [comment]
Note #458 might make this issue go away, but there's been no comments on that yet, so I don't know if it'll land or not.

I will be changing eslint-plugin-mozilla to add the argument, but it seems a bit of a potential pitfall for other developers.

**Comment by soda0289** [comment]
This is related to the fact the escope is monkey patched by babel-eslint on start up.
https://github.com/babel/babel-eslint/blob/master/index.js#L64-L73

We update the monkey patch to at least set the default value of `opts` to `{}` and that would solve your problem
