### ISSUE TITLE
Cannot find module 'escope'

### ISSUE THREAD

**Issue by coljung** [babel/babel-eslint#479]
Currently getting this error when i try to run eslint locally:

```
Error: Cannot find module 'escope'
    at Function.Module._resolveFilename (module.js:455:15)
    at monkeypatch (/Users/pablorincon/Documents/SSENSE/micro-services/ws-website/services/ui-website/node_modules/babel-eslint/index.js:53:26)
    at Object.exports.parse (/Users/pablorincon/Documents/SSENSE/micro-services/ws-website/services/ui-website/node_modules/babel-eslint/index.js:358:5)
    at parse (/Users/pablorincon/Documents/SSENSE/micro-services/ws-website/services/ui-website/node_modules/eslint/lib/linter.js:671:23)
    at Linter.verify (/Users/pablorincon/Documents/SSENSE/micro-services/ws-website/services/ui-website/node_modules/eslint/lib/linter.js:806:27)
    at processText (/Users/pablorincon/Documents/SSENSE/micro-services/ws-website/services/ui-website/node_modules/eslint/lib/cli-engine.js:278:31)
    at processFile (/Users/pablorincon/Documents/SSENSE/micro-services/ws-website/services/ui-website/node_modules/eslint/lib/cli-engine.js:320:18)
    at executeOnFile (/Users/pablorincon/Documents/SSENSE/micro-services/ws-website/services/ui-website/node_modules/eslint/lib/cli-engine.js:655:25)
    at fileList.forEach.fileInfo (/Users/pablorincon/Documents/SSENSE/micro-services/ws-website/services/ui-website/node_modules/eslint/lib/cli-engine.js:693:13)
    at Array.forEach (native)
```

What's weird is that im using the **same** linting configuration with another project, and i had no issues at all.

I'm using:
babel-eslint@7.1.1
eslint@4.0.0-beta.0

Any ideas ?

**Comment by kentcdodds** [comment]
Sorry, I don't know. But if you could reproduce this in another small repo that'd be great :)

**Comment by soda0289** [comment]
You should try to update babel-eslint. ESLint v4 uses a new fork of escope called eslint-scope. babel-eslint v7.2.2 should contain this PR https://github.com/babel/babel-eslint/pull/461 which checks for both

**Comment by coljung** [comment]
Yes, just noticed one of my projects was using 7.1.1 while the other was using 7.2.3

**Comment by coljung** [comment]
That was it, thanks!

**Comment by maxmantz** [comment]
Having the same issue using babel-eslint@7.2.3 & eslint@4.4.1

**Comment by maxmantz** [comment]
Nevermind, clearing my global npm cache and reinstalling resolved the issue.

**Comment by hzoo** [comment]
Cool, and latest eslint should be using a different package now anyway. going to lock
