### ISSUE TITLE
Expected escope dependency breaks eslint 4.0.0

### ISSUE THREAD

**Issue by sutkh** [babel/babel-eslint#490]
When attempting to run eslint 4.0.0 using the babel-eslint parser this error is thrown:

```
Error: Cannot find module 'escope'
    at Function.Module._resolveFilename (module.js:469:15)
    at monkeypatch (/Users/bhallion/workspace/hub-radar/node_modules/babel-eslint/index.js:41:26)
    at Object.exports.parse (/Users/bhallion/workspace/hub-radar/node_modules/babel-eslint/index.js:384:5)
    at parse (/Users/bhallion/workspace/hub-radar/node_modules/eslint/lib/linter.js:671:23)
    at Linter.verify (/Users/bhallion/workspace/hub-radar/node_modules/eslint/lib/linter.js:806:27)
    at processText (/Users/bhallion/workspace/hub-radar/node_modules/eslint/lib/cli-engine.js:278:31)
    at processFile (/Users/bhallion/workspace/hub-radar/node_modules/eslint/lib/cli-engine.js:320:18)
    at executeOnFile (/Users/bhallion/workspace/hub-radar/node_modules/eslint/lib/cli-engine.js:655:25)
    at fileList.forEach.fileInfo (/Users/bhallion/workspace/hub-radar/node_modules/eslint/lib/cli-engine.js:692:13)
    at Array.forEach (native)
```

It seems like eslint 4.0.0 is no longer using this dependency

**Comment by sutkh** [comment]
Ah, I see now that I was using babel-eslint 6.1.2 and that was causing this error

All set
