### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined when adding 'babel-eslint'

### ISSUE THREAD

**Issue by drstonebraker** [babel/babel-eslint#590]
When I add 'babel-eslint' as my parser in my .eslintrc, I get the following error in my eslint output:

[Error - 12:18:40 AM] TypeError: Cannot read property 'replace' of undefined
    at normalizeMessagePlaceholders (/Users/drstonebraker/repos/rhw-estore/webassets/docroot/assets/react/node_modules/eslint/lib/report-translator.js:106:30)
    at /Users/drstonebraker/repos/rhw-estore/webassets/docroot/assets/react/node_modules/eslint/lib/report-translator.js:268:22
    at Object.report (/Users/drstonebraker/repos/rhw-estore/webassets/docroot/assets/react/node_modules/eslint/lib/linter.js:894:62)
    at report (/Users/drstonebraker/repos/rhw-estore/webassets/docroot/assets/react/node_modules/eslint/lib/rules/camelcase.js:69:25)
    at Identifier (/Users/drstonebraker/repos/rhw-estore/webassets/docroot/assets/react/node_modules/eslint/lib/rules/camelcase.js:147:25)
    at listeners.(anonymous function).forEach.listener (/Users/drstonebraker/repos/rhw-estore/webassets/docroot/assets/react/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (/Users/drstonebraker/repos/rhw-estore/webassets/docroot/assets/react/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/drstonebraker/repos/rhw-estore/webassets/docroot/assets/react/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/drstonebraker/repos/rhw-estore/webassets/docroot/assets/react/node_modules/eslint/lib/util/node-event-generator.js:280:22)

I am attempting to use in a create-react-app with eslint-config-airbnb

**Comment by guar47** [comment]
Same thing
```
TypeError: Cannot read property 'replace' of undefined
    at normalizeMessagePlaceholders (/Users/dmitrii/Projects/_GitHub/react-tutorial-tic-tac-toe/node_modules/eslint/lib/report-translator.js:106:30)
    at /Users/dmitrii/Projects/_GitHub/react-tutorial-tic-tac-toe/node_modules/eslint/lib/report-translator.js:268:22
    at Object.report (/Users/dmitrii/Projects/_GitHub/react-tutorial-tic-tac-toe/node_modules/eslint/lib/linter.js:894:62)
    at exitFunction (/Users/dmitrii/Projects/_GitHub/react-tutorial-tic-tac-toe/node_modules/eslint/lib/rules/class-methods-use-this.js:85:25)
    at listeners.(anonymous function).forEach.listener (/Users/dmitrii/Projects/_GitHub/react-tutorial-tic-tac-toe/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (/Users/dmitrii/Projects/_GitHub/react-tutorial-tic-tac-toe/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/dmitrii/Projects/_GitHub/react-tutorial-tic-tac-toe/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/dmitrii/Projects/_GitHub/react-tutorial-tic-tac-toe/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.leaveNode (/Users/dmitrii/Projects/_GitHub/react-tutorial-tic-tac-toe/node_modules/eslint/lib/util/node-event-generator.js:303:14)
```

**Comment by edwinharly** [comment]
It's been a few months, still no fix ?

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
