### ISSUE TITLE
Only output codeframes when eslint would do it

### ISSUE THREAD

**Issue by mogelbrod** [babel/babel-eslint#665]
Eslint currently only includes codeframes when the `stylish` (default) or `codeframe` formatters are used. babel-eslint appears to output them for all formatters however, which tend to break the output:
- **unix:** Codeframe is inserted in the middle of the line, making `[Error]` end up immediately after it
- **table:** Error is thrown since _Table data must not contain control characters._

It would be great if babel-eslint only added codeframes when eslint would do it.

## Current behavior

```shell
$ for formatter in table unix checkstyle compact json tap visualstudio codeframe stylish; do echo -e "\n\n$formatter ========\n" && eslint test.js -f $formatter; done
```

### table (broken)

```shell
Table data must not contain control characters.
Error: Table data must not contain control characters.
    at exports.default.rows (.../node_modules/table/dist/validateTableData.js:47:15)
    at exports.default (.../node_modules/table/dist/table.js:116:35)
    at drawTable (.../node_modules/eslint/lib/formatters/table.js:57:12)
    at results.map.result (.../node_modules/eslint/lib/formatters/table.js:100:43)
    at Array.map (<anonymous>)
    at drawReport (.../node_modules/eslint/lib/formatters/table.js:95:21)
    at module.exports (.../node_modules/eslint/lib/formatters/table.js:127:18)
    at printResults (.../node_modules/eslint/lib/cli.js:91:20)
    at Object.execute (.../node_modules/eslint/lib/cli.js:204:17)
    at Object.<anonymous> (.../node_modules/eslint/bin/eslint.js:79:28)
```

### unix (broken)

```shell
.../test.js:1:9: Parsing error: Unexpected token

> 1 | function()
    |         ^
  2 |  [Error]

1 problem
```

### checkstyle (wrong)

```shell
<?xml version="1.0" encoding="utf-8"?><checkstyle version="4.3"><file name=".../test.js"><error line="1" column="9" severity="error" message="Parsing error: Unexpected token&#10;&#10;&#27;[0m&#27;[31m&#27;[1m&gt;&#27;[22m&#27;[39m&#27;[90m 1 | &#27;[39m&#27;[36mfunction&#27;[39m()&#27;[0m&#10;&#27;[0m &#27;[90m   | &#27;[39m        &#27;[31m&#27;[1m^&#27;[22m&#27;[39m&#27;[0m&#10;&#27;[0m &#27;[90m 2 | &#27;[39m&#27;[0m" source="" /></file></checkstyle>
```

### compact (wrong)

```shell
.../test.js: line 1, col 9, Error - Parsing error: Unexpected token

> 1 | function()
    |         ^
  2 |

1 problem
```

### json (wrong)

```shell
[{"filePath":".../test.js","messages":[{"ruleId":null,"fatal":true,"severity":2,"message":"Parsing error: Unexpected token\n\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 1 | \u001b[39m\u001b[36mfunction\u001b[39m()\u001b[0m\n\u001b[0m \u001b[90m   | \u001b[39m        \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 2 | \u001b[39m\u001b[0m","line":1,"column":9}],"errorCount":1,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"source":"function()\n"}]
```

### tap (wrong)

```shell
TAP version 13
1..1
not ok 1 - .../test.js
  ---
  message: "Parsing error: Unexpected token\n\n\e[0m\e[31m\e[1m>\e[22m\e[39m\e[90m 1 | \e[39m\e[36mfunction\e[39m()\e[0m\n\e[0m \e[90m   | \e[39m        \e[31m\e[1m^\e[22m\e[39m\e[0m\n\e[0m \e[90m 2 | \e[39m\e[0m"
  severity: error
  data:
    line: 1
    column: 9
    ruleId: ''
  ...
```

### visualstudio (wrong)

```shell
.../test.js(1,9): error : Parsing error: Unexpected token

> 1 | function()
    |         ^
  2 |

1 problem
```

### codeframe (correct)

```shell
error: Parsing error: Unexpected token

> 1 | function()
    |         ^
  2 |  at test.js:1:9:
> 1 | function()
    |         ^
  2 |


1 error found.
```

### stylish (correct)

```shell
.../test.js
  1:9  error  Parsing error: Unexpected token

> 1 | function()
    |         ^
  2 |

✖ 1 problem (1 error, 0 warnings)
```

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
