### ISSUE TITLE
Cannot read property 'type' of undefined with ES Class Properties

### ISSUE THREAD

**Issue by skevy** [babel/babel-eslint#71]
Hi there - 

This code:

```javascript
class TestClass {
  aMethod = (e) => {
    return true;
  }
}
```

causes eslint to fail (with babel-eslint turned on, of course) with:

```
/Users/adam/.nvm/v0.12.0/lib/node_modules/eslint/lib/rules/no-unused-vars.js:121
                if (type === "Parameter" && def.node.parent.type === "Property
                                                           ^
TypeError: Cannot read property 'type' of undefined
    at getUnusedLocals (/Users/adam/.nvm/v0.12.0/lib/node_modules/eslint/lib/rules/no-unused-vars.js:121:60)
    at Array.map (native)
    at getUnusedLocals (/Users/adam/.nvm/v0.12.0/lib/node_modules/eslint/lib/rules/no-unused-vars.js:141:58)
    at Array.map (native)
    at getUnusedLocals (/Users/adam/.nvm/v0.12.0/lib/node_modules/eslint/lib/rules/no-unused-vars.js:141:58)
    at Array.map (native)
    at getUnusedLocals (/Users/adam/.nvm/v0.12.0/lib/node_modules/eslint/lib/rules/no-unused-vars.js:141:58)
    at Array.map (native)
    at getUnusedLocals (/Users/adam/.nvm/v0.12.0/lib/node_modules/eslint/lib/rules/no-unused-vars.js:141:58)
    at EventEmitter.Program:exit (/Users/adam/.nvm/v0.12.0/lib/node_modules/eslint/lib/rules/no-unused-vars.js:147:26)
```

This is using eslint 0.19.0 and babel-eslint 3.0.1.

**Comment by Dignifiedquire** [comment]
Seeing the same issue myself. Same versions as above

**Comment by koistya** [comment]
```js
class Foo {
  a = () => { console.log('test'); };
}
```

```
TypeError: Cannot read property 'type' of undefined
    at hasTypeOfOperator (.\node_modules\eslint\lib\rules\no-undef.js:53:18)
    at .\node_modules\eslint\lib\rules\no-undef.js:75:21
    at Array.forEach (native)
    at EventEmitter.Program:exit (.\node_modules\eslint\lib\rules\no-undef.js:71:33)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.leave (.\node_modules\eslint\lib\eslint.js:734:25)
    at Controller.__execute (.\node_modules\eslint\node_modules\estraverse\estraverse.js:393:31)
    at Controller.traverse (.\node_modules\eslint\node_modules\estraverse\estraverse.js:481:28)
    at EventEmitter.module.exports.api.verify (.\node_modules\eslint\lib\eslint.js:719:24)
    at processFile (.\node_modules\eslint\lib\cli-engine.js:195:27)
```

https://github.com/eslint/eslint/blob/14a49bb401815242d2e8f614724d58a2796dd203/lib/rules/no-undef.js#L52

**Comment by danro** [comment]
+1 same error here.. my use case:
```js
class Foo {
  static props = {
    bar: staticTest()
  };
}
```

**Comment by b2whats** [comment]
+1 same error

**Comment by doctyper** [comment]
I just ran into this issue. I fixed it locally by editing a file in `eslint` proper:
https://github.com/eslint/eslint/blob/master/lib/rules/no-unused-vars.js#L121

from:

```js
if (type === "Parameter" && def.node.parent.type === "Property" && def.node.parent.kind === "set") {
```

to:

```js
if (type === "Parameter" && def.node.parent && def.node.parent.type === "Property" && def.node.parent.kind === "set") {
```

My question is, is this a fix or just a workaround? If the former I can PR this into ESLint.

**Comment by sebmck** [comment]
Should be fixed via #73 and released as of v3.1.1. Those of you effected by this issue please confirm that the latest fixes this.

**Comment by playpauseandstop** [comment]
Confirmed! The lint is back!

**Comment by koistya** [comment]
Works good, thanks!

**Comment by yordis** [comment]
@hzoo I have this issue: `Uncaught TypeError: Cannot read property 'value' of undefined` I am trying to use class properties.

```
...
get isEmptyMessage() {
    const { value } = this.state

    return Boolean(value.trim().length)
  }
...
```

`package.json`
```
{
"babel-core": "^6.3.26",
"babel-loader": "^6.2.0",
"babel-preset-es2015": "^6.3.13",
"babel-preset-react": "^6.3.13",
"babel-preset-stage-1": "^6.3.13",
"babel-plugin-transform-decorators-legacy": "^1.3.4" // I don't load it in the plugins so I don't know if this matter
}
```

`.babelrc`
```
{
  "presets": [
    "stage-1",
    "es2015",
    "react"
  ],
  "plugins": [
    "transform-class-properties"
  ]
}

```
