### ISSUE TITLE
Unknown node type ExportNamespaceSpecifier

### ISSUE THREAD

**Issue by ooflorent** [babel/babel-eslint#73]
`babel-eslint` fails to parse ES7 module exports (but compilation is OK):

```
> eslint src/ test/

/Users/fc/Development/ooflorent/parsly/node_modules/eslint/node_modules/estraverse/estraverse.js:511
                        throw new Error('Unknown node type ' + nodeType + '.')
                              ^
Error: Unknown node type ExportDefaultSpecifier.
    at Controller.traverse (/Users/fc/Development/ooflorent/parsly/node_modules/eslint/node_modules/estraverse/estraverse.js:511:31)
    at EventEmitter.module.exports.api.verify (/Users/fc/Development/ooflorent/parsly/node_modules/eslint/lib/eslint.js:719:24)
    at processFile (/Users/fc/Development/ooflorent/parsly/node_modules/eslint/lib/cli-engine.js:195:27)
    at /Users/fc/Development/ooflorent/parsly/node_modules/eslint/lib/cli-engine.js:295:26
    at /Users/fc/Development/ooflorent/parsly/node_modules/eslint/lib/util/traverse.js:61:17
    at Array.forEach (native)
    at traverse (/Users/fc/Development/ooflorent/parsly/node_modules/eslint/lib/util/traverse.js:41:54)
    at walk (/Users/fc/Development/ooflorent/parsly/node_modules/eslint/lib/util/traverse.js:83:9)
    at /Users/fc/Development/ooflorent/parsly/node_modules/eslint/lib/util/traverse.js:102:9
    at Array.forEach (native)
```

**index.js**

```js
export * as Parser from './parser'
export Transform from './transform'
```

**.babelrc**
```js
{
  "stage": 0,
  "loose": true
}
```

**.eslintrc**
```yml
---
parser: "babel-eslint"
env:
  es6: true
```

**Comment by srph** [comment]
@ooflorent Have you solved this issue? I'm having the same issue as well

**Comment by ooflorent** [comment]
I've stopped using ES7 exports.

Le dimanche 3 mai 2015, Kier Borromeo <notifications@github.com> a écrit :

> @ooflorent <https://github.com/ooflorent> Have you solved this issue? I'm
> having the same issue as well
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel-eslint/issues/73#issuecomment-98436913>.
>


-- 
Florent Cailhol

**Comment by srph** [comment]
Awesome! Thanks.
