### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by DLevai94** [babel/babel-eslint#742]
* **ESLint Version:** v5.4.0
* **Node Version:** v11.6.0
* **npm Version:** v6.5.0-next.0

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint with React Native

<details>
<summary>Configuration</summary>

```js
{
  "env": {
    "browser": true,
    "jest": true
  },
  "extends": [
    "airbnb",
    "plugin:prettier/recommended",
    "plugin:flowtype/recommended"
  ],
  "parser": "babel-eslint",
  "plugins": ["react", "jsx-a11y", "import", "flowtype"],
  "globals": {
    "window": true
  },
  "rules": {
    "react/jsx-filename-extension": 0,
    "react/sort-comp": 0,
    "react/destructuring-assignment": 0,
    "react/jsx-wrap-multilines": 0,
    "react/no-access-state-in-setstate": 0,
    "react/jsx-one-expression-per-line": 0,
    "import/no-named-as-default": 0,
    "linebreak-style": 0,
    "jsx-a11y/href-no-hash": 0,
    "no-unused-expressions": "off",
    "react/forbid-prop-types": 0,
    "no-restricted-globals": "off",
    "import/prefer-default-export": 0,
    "no-console": 0,
    "camelcase": 0,
    "no-shadow": 0,
    "no-plusplus": 0,
    "import/no-extraneous-dependencies": 0,
    "import/named": 0,
    "import/no-unresolved": [2, { "ignore": ["^@"] }],
    "import/extensions": [2, { "ignore": ["^@"] }],
    "consistent-return": 0,
    "no-param-reassign": 0,
    "no-nested-ternary": 0,
    "prettier/prettier": [
      "error",
      {
        "bracketSpacing": true,
        "singleQuote": true,
        "trailingComma": "es5",
        "jsxBracketSameLine": false,
        "parser": "flow",
        "useTabs": false,
        "tabWidth": 2
      }
    ],
  },
  "settings": {
    "import/resolver": {
      "node": {
        "extensions": [".js", ".android.js", ".ios.js"]
      }
    }
  }
}

```

</details>

```js
RangeError: Maximum call stack size exceeded
    at Function.keys (<anonymous>)
    at hashObject (/Users/davidlevai/Desktop/Work/Classy/Projects/BES/bybesapp/node_modules/eslint-module-utils/hash.js:46:10)
    at hashify (/Users/davidlevai/Desktop/Work/Classy/Projects/BES/bybesapp/node_modules/eslint-module-utils/hash.js:18:5)
    at Object.keys.sort.forEach.key (/Users/davidlevai/Desktop/Work/Classy/Projects/BES/bybesapp/node_modules/eslint-module-utils/hash.js:49:5)
    at Array.forEach (<anonymous>)
    at hashObject (/Users/davidlevai/Desktop/Work/Classy/Projects/BES/bybesapp/node_modules/eslint-module-utils/hash.js:46:30)
    at hashify (/Users/davidlevai/Desktop/Work/Classy/Projects/BES/bybesapp/node_modules/eslint-module-utils/hash.js:18:5)
    at Object.keys.sort.forEach.key (/Users/davidlevai/Desktop/Work/Classy/Projects/BES/bybesapp/node_modules/eslint-module-utils/hash.js:49:5)
    at Array.forEach (<anonymous>)
    at hashObject (/Users/davidlevai/Desktop/Work/Classy/Projects/BES/bybesapp/node_modules/eslint-module-utils/hash.js:46:30)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```bash
./node_modules/.bin/eslint --cache --fix ./src
```

**What did you expect to happen?**
Run

**What actually happened? Please include the actual, raw output from ESLint.**
```
RangeError: Maximum call stack size exceeded
    at Function.keys (<anonymous>)
    at hashObject (/Users/davidlevai/Desktop/Work/Classy/Projects/BES/bybesapp/node_modules/eslint-module-utils/hash.js:46:10)
    at hashify (/Users/davidlevai/Desktop/Work/Classy/Projects/BES/bybesapp/node_modules/eslint-module-utils/hash.js:18:5)
    at Object.keys.sort.forEach.key (/Users/davidlevai/Desktop/Work/Classy/Projects/BES/bybesapp/node_modules/eslint-module-utils/hash.js:49:5)
    at Array.forEach (<anonymous>)
    at hashObject (/Users/davidlevai/Desktop/Work/Classy/Projects/BES/bybesapp/node_modules/eslint-module-utils/hash.js:46:30)
    at hashify (/Users/davidlevai/Desktop/Work/Classy/Projects/BES/bybesapp/node_modules/eslint-module-utils/hash.js:18:5)
    at Object.keys.sort.forEach.key (/Users/davidlevai/Desktop/Work/Classy/Projects/BES/bybesapp/node_modules/eslint-module-utils/hash.js:49:5)
    at Array.forEach (<anonymous>)
    at hashObject (/Users/davidlevai/Desktop/Work/Classy/Projects/BES/bybesapp/node_modules/eslint-module-utils/hash.js:46:30)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Are you willing to submit a pull request to fix this bug?**
No. I don't know what causes the issue.

**Comment by DLevai94** [comment]
Fixed here. https://github.com/eslint/eslint/issues/11274
