### ISSUE TITLE
Rules breaking in 3.1.2

### ISSUE THREAD

**Issue by kentcdodds** [babel/babel-eslint#96]
Something in [these changes](https://github.com/babel/babel-eslint/compare/v3.1.1...v3.1.2) broke my eslinting. I'm using the `eslint-loader` for webpack as well. I'm not certain what the core issue is, but here's the error I'm seeing:

```
ERROR in ./app/components/index.js
Module build failed: TypeError: Cannot read property 'value' of undefined
    at EventEmitter.detectOpenSpaces (/Users/kentcdodds/Developer/alianza/atac5/node_modules/eslint/lib/rules/no-spaced-func.js:18:34)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:166:7)
    at Controller.controller.traverse.enter (/Users/kentcdodds/Developer/alianza/atac5/node_modules/eslint/lib/eslint.js:726:25)
    at Controller.__execute (/Users/kentcdodds/Developer/alianza/atac5/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (/Users/kentcdodds/Developer/alianza/atac5/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (/Users/kentcdodds/Developer/alianza/atac5/node_modules/eslint/lib/eslint.js:719:24)
    at processText (/Users/kentcdodds/Developer/alianza/atac5/node_modules/eslint/lib/cli-engine.js:227:23)
    at CLIEngine.executeOnText (/Users/kentcdodds/Developer/alianza/atac5/node_modules/eslint/lib/cli-engine.js:338:22)
    at lint (/Users/kentcdodds/Developer/alianza/atac5/node_modules/eslint-loader/index.js:17:20)
 @ ./app/index.js 8:0-23
```

And here's the code that the error is being thrown on (specific line commented):

```javascript
/**
 * @fileoverview Rule to check that spaced function application
 * @author Matt DuVall <http://www.mattduvall.com>
 */

"use strict";

//------------------------------------------------------------------------------
// Rule Definition
//------------------------------------------------------------------------------

module.exports = function(context) {

    function detectOpenSpaces(node) {
        var lastCalleeToken = context.getLastToken(node.callee);
        var tokens = context.getTokens(node);
        var i = tokens.indexOf(lastCalleeToken), l = tokens.length;
        while (i < l && tokens[i].value !== "(") { ///////////////////////////////////////////////////////////////////////// <-- that line
            ++i;
        }
        if (i >= l) {
            return;
        }
        // look for a space between the callee and the open paren
        if (tokens[i - 1].range[1] !== tokens[i].range[0]) {
            context.report(node, "Unexpected space between function name and paren.");
        }
    }

    return {
        "CallExpression": detectOpenSpaces,
        "NewExpression": detectOpenSpaces
    };

};
```

I believe that if I turn off this rule, a similar error is thrown for a different rule.

**Comment by sebmck** [comment]
Can you gist a reproducible example that produces this error in `./app/components/index.js`?

**Comment by mtscout6** [comment]
I'm getting the same problem in [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap) which had no linting errors or warnings prior to this release. You can see it on the latest master branch now.

**Comment by kentcdodds** [comment]
Hmmm... Having difficulty reproducing a small example... I'll try to get one for you when I get more time later.

**Comment by AlexKVal** [comment]
I've found the "gist" substitute.
I hope it would help.

With this file https://github.com/react-bootstrap/react-bootstrap/blob/master/webpack/strategies/docs-development.js
```sh
› eslint webpack/strategies/docs-development.js 
/Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/rules/no-empty-class.js:36
            if (token.type === "RegularExpression" && !regex.test(token.value)
                     ^
TypeError: Cannot read property 'type' of undefined
    at EventEmitter.Literal (/Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/rules/no-empty-class.js:36:22)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter (/Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/eslint.js:726:25)
    at Controller.__execute (/Users/alexkval/src/js/react-bootstrap/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (/Users/alexkval/src/js/react-bootstrap/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (/Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/eslint.js:719:24)
    at processFile (/Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/cli-engine.js:197:27)
    at /Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/cli-engine.js:332:26
    at walk (/Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/util/traverse.js:81:9)
    at /Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/util/traverse.js:102:9
```

And there were no these errors before `babel-eslint@3.12`
https://github.com/AlexKVal/react-bootstrap/blob/master/webpack/webpack.config.js#L48
```sh
› eslint webpack/webpack.config.js 

webpack/webpack.config.js
  48:16  error  Empty class  no-empty-class
  48:50  error  Empty class  no-empty-class
```

**Comment by hzoo** [comment]
If `tokens[i]` is undefined then it's probably the last commit with the Template change =(. I'l look into this.

**Comment by AlexKVal** [comment]
This output is without https://github.com/babel/babel-eslint/pull/94
```sh
› eslint webpack/strategies/docs-development.js

webpack/strategies/docs-development.js
  20:14  error  Empty class  no-empty-class

✖ 1 problem (1 error, 0 warnings)
```

And all is clean without this https://github.com/babel/babel-eslint/pull/93

I hope it helps. :tada:

**Comment by taion** [comment]
This is the simplest case I can find that triggers the exception:

```js
export default function f1() {
  function f2(foo) {
    const bar = 3;
    return `${foo} ${bar}`;
  }
  return f2;
}
```

**Comment by hzoo** [comment]
Thanks everyone - I understand the issue now.

**Comment by hzoo** [comment]
Ok able to fix @taion's code snippet.

Running `npm lint` on `react-bootstrap` I also don't get the error anymore, except I'm getting eslint errors for `no-empty-class` and `space-infix-ops` which might be from #93?

**Comment by taion** [comment]
Can we back out these changes pending further testing? Right now 3.1.2 is causing issues for users.

**Comment by sebmck** [comment]
I've removed `3.1.2` from npm pending #97.

**Comment by dozoisch** [comment]
@hzoo @sebmck (another react-bootstrap maintainer here) Thanks guys for the quick answer!

**Comment by hzoo** [comment]
Can everyone test on the PR in #97?

**Comment by AlexKVal** [comment]
https://github.com/babel/babel-eslint/pull/97#issuecomment-102345177
